"""Brief domain model (Section 9, tables `generated_briefs`/`brief_claims`;
Section 12.3 Stage C; ADR-011). Two distinct kinds of shape live here:

- **Persisted rows** (`GeneratedBrief`, `BriefClaimRecord`) — what
  `project_context.db.brief_repository` reads back from SQLite, one to
  one with the migration 0008 schema.
- **The deterministic fact payload** (`BriefFact`, `BriefFactSection`,
  `CurrentProjectBriefFacts`) — never persisted as its own table; it is
  built fresh by `project_context.retrieval.briefs` from accepted ledger
  state, frozen verbatim into `generated_briefs.input_snapshot_json` for
  reproducibility (Section 8: "Store brief, inputs, output..."), and is
  the *only* thing the Stage C model ever sees (ADR-011: "Prevents brief
  model from reinterpreting whole corpus"). It never carries raw
  evidence quotes or chunk text — only already-validated structured
  fields plus opaque `evidence_link_ids` (Section 12.3: "allowed fact ID,
  current value, status, dates, owner, change type, and evidence-link
  IDs").
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict


class BriefType(StrEnum):
    """Matches the `generated_briefs.brief_type` CHECK constraint
    exactly. Only `CURRENT_PROJECT` is generated by this prompt's
    service; `MEETING_PREPARATION` is schema-ready (FR-025) but has no
    generator yet."""

    CURRENT_PROJECT = "current_project"
    MEETING_PREPARATION = "meeting_preparation"


class BriefStatus(StrEnum):
    """Matches the `generated_briefs.status` CHECK constraint exactly.
    `SUPERSEDED` is set on a project's previous `VALID` brief of the same
    `brief_type` the moment a new one is accepted — "stored brief
    history" (Prompt 9) means every past brief stays queryable, not that
    more than one counts as current at a time."""

    GENERATING = "generating"
    VALID = "valid"
    FAILED = "failed"
    SUPERSEDED = "superseded"


class ClaimType(StrEnum):
    """Matches `brief_claims.claim_type` (Section 9's `BriefClaim.claim_type`
    pattern) exactly. `FACT`/`INFERENCE` must cite at least one fact
    (Prompt 9: "Any inference must cite the facts supporting it");
    `SUGGESTION` need not, since it is not an assertion about project
    state at all."""

    FACT = "fact"
    INFERENCE = "inference"
    SUGGESTION = "suggestion"


class ClaimValidationStatus(StrEnum):
    """Matches `brief_claims.validation_status` exactly."""

    VALID = "valid"
    UNSUPPORTED = "unsupported"
    INVALID_REFERENCE = "invalid_reference"


class GeneratedBrief(BaseModel):
    """A `generated_briefs` row as stored. See migrations/0008_briefs.sql."""

    id: str
    project_id: str
    brief_type: BriefType
    meeting_artifact_id: str | None
    cutoff_at: str
    input_snapshot: dict[str, Any]
    markdown: str | None
    model_id: str | None
    prompt_version: str | None
    schema_version: str | None
    status: BriefStatus
    input_tokens: int | None
    output_tokens: int | None
    estimated_cost_usd: float | None
    latency_ms: int | None
    safe_error: str | None
    created_at: str


class BriefClaimRecord(BaseModel):
    """A `brief_claims` row as stored. See migrations/0008_briefs.sql and
    that migration's header for how this differs from Section 9's
    representative `BriefClaim` wire schema."""

    id: str
    project_id: str
    brief_id: str
    section: str
    ordinal: int
    claim_text: str
    claim_type: ClaimType
    ledger_item_id: str | None
    ledger_version_id: str | None
    cited_fact_ids: tuple[str, ...]
    validation_status: ClaimValidationStatus
    created_at: str


# ---------------------------------------------------------------------------
# The deterministic fact payload (never persisted as its own table — see
# module docstring).
# ---------------------------------------------------------------------------


class BriefFactType(StrEnum):
    """What kind of accepted-state fact this is — controls which fields
    are meaningful and how the renderer/prompt describe it."""

    #: The project record itself (objective/description/stage) — not
    #: tied to any ledger item, and does not require evidence to be
    #: valid (Section 5.8's "objective and scope" section; its own
    #: evidence *is* the project record, always resolvable).
    PROJECT_META = "project_meta"
    #: One ledger item's current accepted state (Section 8: "current
    #: ledger items... most recent accepted version").
    CURRENT_STATE = "current_state"
    #: One specific accepted transition/version — "recent changes"
    #: (Section 5.8): what changed, and (for updates) what it changed
    #: from.
    TRANSITION = "transition"


class BriefFact(BaseModel):
    """One atomic, already-resolved fact the Stage C model may cite by
    its opaque `fact_id` — never by raw ledger/evidence IDs directly
    (Section 12.4: "Keep evidence IDs opaque and supplied by the app").
    Every field is already-validated structured data; no evidence quotes
    or source text are included (Prompt 9: "not source chunks or
    arbitrary search results")."""

    model_config = ConfigDict(frozen=True)

    fact_id: str
    section: str
    fact_type: BriefFactType
    kind: str | None = None
    ledger_item_id: str | None = None
    ledger_version_id: str | None = None
    title: str
    detail: str | None = None
    status: str | None = None
    owner_name: str | None = None
    due_date: str | None = None
    effective_at: str | None = None
    transition_type: str | None = None
    #: For a TRANSITION fact only: a short, deterministic description of
    #: the prior value (e.g. "was due 2026-08-28"), so a claim like "the
    #: due date moved to Sep 4" is traceable without the model inventing
    #: the old value itself.
    previous_summary: str | None = None
    evidence_link_ids: tuple[str, ...] = ()


class BriefFactSection(BaseModel):
    """One of the Current Project Brief's required sections and its
    facts. An empty `facts` tuple is meaningful and expected — Prompt 9:
    "Missing sections must be explicit and honest" — and is rendered
    deterministically by the service, never sent to the model at all
    (see `project_context.services.briefs`)."""

    model_config = ConfigDict(frozen=True)

    section: str
    heading: str
    facts: tuple[BriefFact, ...] = ()


#: The eight required Current Project Brief sections, in the fixed order
#: FR-024/Section 5.8 specify — the application owns this structure, not
#: the model (see project_context.services.briefs's module docstring for
#: why the model is never asked to invent section headings).
CURRENT_BRIEF_SECTIONS: tuple[tuple[str, str], ...] = (
    ("objective_and_scope", "Objective and Scope"),
    ("current_stage", "Current Stage"),
    ("recent_changes", "Recent Changes"),
    ("next_milestone", "Next Milestone"),
    ("open_commitments", "Open Commitments"),
    ("decisions", "Decisions"),
    ("risks_and_blockers", "Risks and Blockers"),
    ("unresolved_questions", "Unresolved Questions"),
)


class CurrentProjectBriefFacts(BaseModel):
    """The full deterministic input to one Current Project Brief
    generation run — exactly what gets frozen into
    `generated_briefs.input_snapshot_json` (Prompt 9: "Store the exact
    deterministic input snapshot so generation is reproducible")."""

    model_config = ConfigDict(frozen=True)

    project_id: str
    generated_at: str
    sections: tuple[BriefFactSection, ...]

    def fact_by_id(self) -> dict[str, BriefFact]:
        """Every fact across every section, keyed by its opaque
        `fact_id` — the one lookup table claim validation ever consults
        (`project_context.services.briefs`)."""
        return {
            fact.fact_id: fact for section in self.sections for fact in section.facts
        }
